
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 27 19:10:30 CST 2017
//----------------------------------------------------

package mini.pascal.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 33;
  public static final int STRING_LITERAL = 56;
  public static final int RIGHT_BRACKET = 24;
  public static final int CHAR = 46;
  public static final int EQUALS = 37;
  public static final int LEFT_KEY = 47;
  public static final int NOT_EQUAL = 38;
  public static final int XOR = 35;
  public static final int INTEGER = 43;
  public static final int REPEAT = 17;
  public static final int ARRAY = 6;
  public static final int PRODUCT = 34;
  public static final int FOR = 19;
  public static final int MINUS = 32;
  public static final int GREATER_THAN = 39;
  public static final int READ_LN = 49;
  public static final int NOT = 11;
  public static final int SEMICOLON = 26;
  public static final int AND = 5;
  public static final int IN = 25;
  public static final int OR = 13;
  public static final int COMMA = 28;
  public static final int WRITE_LN = 48;
  public static final int DIV = 7;
  public static final int BEGIN = 3;
  public static final int LESS_EQUAL = 42;
  public static final int UNTIL = 18;
  public static final int PLUS = 31;
  public static final int GREATER_EQUALS = 41;
  public static final int IF = 10;
  public static final int ID = 44;
  public static final int DOT = 29;
  public static final int OF = 12;
  public static final int BOOLEAN = 50;
  public static final int EOF = 0;
  public static final int TRUE = 52;
  public static final int INT_CONST = 51;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 36;
  public static final int RIGHT_PAR = 22;
  public static final int COLON = 27;
  public static final int CHAR_CONS = 54;
  public static final int ELSE = 9;
  public static final int TO = 20;
  public static final int WHILE = 16;
  public static final int THEN = 14;
  public static final int ASIGN = 30;
  public static final int END = 4;
  public static final int RIGHT_KEY = 55;
  public static final int STRING = 45;
  public static final int FALSE = 53;
  public static final int LEFT_PAR = 21;
  public static final int LESS_THAN = 40;
  public static final int LEFT_BRACKET = 23;
  public static final int VAR = 15;
  public static final int DO = 8;
}

