
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 22 19:49:47 CST 2017
//----------------------------------------------------

package mini.pascal.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 30;
  public static final int STRING_LITERAL = 53;
  public static final int RIGHT_BRACKET = 22;
  public static final int CHAR = 43;
  public static final int EQUALS = 34;
  public static final int LEFT_KEY = 44;
  public static final int NOT_EQUAL = 35;
  public static final int XOR = 32;
  public static final int INTEGER = 40;
  public static final int ARRAY = 6;
  public static final int PRODUCT = 31;
  public static final int MINUS = 29;
  public static final int GREATER_THAN = 36;
  public static final int READ_LN = 46;
  public static final int NOT = 11;
  public static final int SEMICOLON = 23;
  public static final int AND = 5;
  public static final int OR = 13;
  public static final int COMMA = 25;
  public static final int WRITE_LN = 45;
  public static final int DIV = 7;
  public static final int BEGIN = 3;
  public static final int LESS_EQUAL = 39;
  public static final int PLUS = 28;
  public static final int GREATER_EQUALS = 38;
  public static final int QUOTE = 18;
  public static final int IF = 10;
  public static final int ID = 41;
  public static final int DOT = 26;
  public static final int OF = 12;
  public static final int BOOLEAN = 47;
  public static final int EOF = 0;
  public static final int TRUE = 49;
  public static final int INT_CONST = 48;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 33;
  public static final int RIGHT_PAR = 20;
  public static final int COLON = 24;
  public static final int CHAR_CONS = 51;
  public static final int ELSE = 9;
  public static final int WHILE = 17;
  public static final int THEN = 15;
  public static final int ASIGN = 27;
  public static final int END = 4;
  public static final int RIGHT_KEY = 52;
  public static final int STRING = 42;
  public static final int FALSE = 50;
  public static final int LEFT_PAR = 19;
  public static final int LESS_THAN = 37;
  public static final int LEFT_BRACKET = 21;
  public static final int VAR = 16;
  public static final int PROCEDURE = 14;
  public static final int DO = 8;
}

