
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 28 15:40:06 CST 2017
//----------------------------------------------------

package mini.pascal.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 32;
  public static final int STRING_LITERAL = 52;
  public static final int RIGHT_BRACKET = 23;
  public static final int CHAR = 44;
  public static final int EQUALS = 35;
  public static final int NOT_EQUAL = 36;
  public static final int INTEGER = 41;
  public static final int REPEAT = 16;
  public static final int ARRAY = 5;
  public static final int PRODUCT = 33;
  public static final int FOR = 18;
  public static final int MINUS = 31;
  public static final int GREATER_THAN = 37;
  public static final int READ_LN = 46;
  public static final int NOT = 10;
  public static final int SEMICOLON = 25;
  public static final int IN = 24;
  public static final int OR = 12;
  public static final int COMMA = 27;
  public static final int WRITE_LN = 45;
  public static final int DIV = 6;
  public static final int BEGIN = 3;
  public static final int LESS_EQUAL = 40;
  public static final int UNTIL = 17;
  public static final int PLUS = 30;
  public static final int GREATER_EQUALS = 39;
  public static final int IF = 9;
  public static final int ID = 42;
  public static final int DOT = 28;
  public static final int OF = 11;
  public static final int BOOLEAN = 47;
  public static final int EOF = 0;
  public static final int TRUE = 49;
  public static final int INT_CONST = 48;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 34;
  public static final int RIGHT_PAR = 21;
  public static final int COLON = 26;
  public static final int CHAR_CONS = 51;
  public static final int ELSE = 8;
  public static final int TO = 19;
  public static final int WHILE = 15;
  public static final int THEN = 13;
  public static final int ASIGN = 29;
  public static final int END = 4;
  public static final int STRING = 43;
  public static final int FALSE = 50;
  public static final int LEFT_PAR = 20;
  public static final int LESS_THAN = 38;
  public static final int LEFT_BRACKET = 22;
  public static final int VAR = 14;
  public static final int DO = 7;
}

